version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: hospital_db
    ports:
      - "3307:3306"  # 👈 Host port 3307 maps to container's 3306
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
